### ISSUE TITLE
Demo dashboard error

### ISSUE THREAD

**Issue by RakowskiPrzemyslaw** [stripe/stripe-demo-connect-kavholm-marketplace#28]
https://kavholm.com/dashboard 
this page doesn't load properly due to this error 
![image](https://user-images.githubusercontent.com/33127342/143770970-f8912796-45b2-4fd9-a05e-b93cf5395057.png)

**Comment by rontomo** [comment]
So what should I do now?

**Comment by cjavilla-stripe** [comment]
Hey @rontomo and @RakowskiPrzemyslaw, 

There was a regression when we upgraded the version of next.js which is now fixed and deployed. Thanks for the heads up.
