### ISSUE TITLE
string concatenation on listing prices

### ISSUE THREAD

**Issue by scottjodoin** [stripe/stripe-demo-connect-kavholm-marketplace#9]
On the listing page, prices are added as strings for user-created listings.

e.g. User creates a listing with price 1 USD
The api returns total amount 0 + "100" + 10 = "010010" in the reduce() function

expected behaviour should be returning 110 (as a number, not a string)

To fix this problem change the following:

# pages/api/listings/new.js

line 22 should say:

      price: {
        amount: parseInt(price), 
        currency: currency,
      },

Cheers.

**Comment by scottjodoin** [comment]
I made a pull request for this issue.

**Comment by auchenberg-stripe** [comment]
Fixed in https://github.com/stripe/stripe-demo-connect-kavholm-marketplace/pull/10
